server:
  port: 9101

turbine:
  app-config: microcloud-provider-dept
  cluster-name-expression: new String("default")


eureka:
  client:
    service-url:
      defaultZone : http://admin:123456@eureka-7001.com:7001/eureka/,http://admin:123456@eureka-7002.com:7002/eureka/,http://admin:123456@eureka-7003.com:7003/eureka/
    register-with-eureka: false