server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone : http://admin:123456@eureka-7001.com:7001/eureka/,http://admin:123456@eureka-7002.com:7002/eureka/,http://admin:123456@eureka-7003.com:7003/eureka/
    register-with-eureka: false



feign:
  hystrix:
    enabled: true  #默认关闭
  compression:
    request:
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    default:
  circuitBreaker:
    enabled: true
    requestVolumeThreshold: 20 #触发熔断的最小请求次数，默认20
    sleepWindowInMilliseconds: 10000 #熔断多少秒后去尝试请求
    errorThresholdPercentage: 50 #触发熔断的失败请求最小占比，默认50%
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000


management:
  endpoints:
    web:
      exposure:
        include: "*"  ##actuator 只看开放了info、health


logging:
  level:
     root: debug
