server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone : http://admin:123456@eureka-7001.com:7001/eureka/,http://admin:123456@eureka-7002.com:7002/eureka/,http://admin:123456@eureka-7003.com:7003/eureka/
  instance :
    instance-id : dept-8001.com  #在状态status显示，信息列表显示主机名称
    prefer-ip-address: true      #访问路径变为ip地址
    lease-renewal-interval-in-seconds: 4   #设置心跳的时间间隔,默认30秒
    lease-expiration-duration-in-seconds: 12 #三个心跳时间，超过此间隔时间，就认为服务挂了！！


management:
  security:
    enabled: true # acutator组件，默认true
info:
   app.name : ${spring.application.name}
   app.artifactId : $project.artifactId$
   app.version : $project.version$

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源类型
    driver-class-name: com.mysql.jdbc.Driver   #mysql驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/spring_test?useUnicode=true&characterEncoding=utf8  #编码不加，可能会乱码
    username: root
    password: 121842276
    filters : stat,wall,log4j  #数据源监控配置
    dbcp2:
      initial-size: 5        #初始化提供的连接数
      min-idle: 5            #数据库连接池维持的最小连接数
      max-total: 20          #最大连接数
      max-wait-millis: 200   #等待连接的最大超时时间,单位ms
  application:
    name: microcloud-provider-dept  #服务的名称


mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  mapper-locations: classpath*:mybatis/**/*.xml     #mapper.xml配置文件
  type-aliases-package: com.it      #设置类的别名,然后在mapper的xml文件中设置

##pageHelper的配置
pagehelper:
  reasonable: false        #是否禁用合理化,（BUG）目前发现false的时候，pageNum<1，有数据返回
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据

  auto-dialect: true       #是否检测dialect
  #dialect: mysql          #加了会回报错，用上面也是可以的


###下面的配置会改成代码配置模块的形式-microcloud-security
#security:
#  basic:
#    enabled: true  #启用springsecurity的安全配置项
#  user:
#    name: admin
#    password: 123456
#    role:
#      - USER      #这个不配置可能会报错
#  sessions: stateless #默认无状态的,这个配置有效，必须上面的enable=true

security:
  ignored:
    - /hystrix.stream
    - /turbine.stream