server:
  port: 7001

eureka:
  instance:
    hostname: eureka-7001.com #eureka实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000  #设置清理服务的间隔时间，单位毫秒，默认60毫秒
  client:
    register-with-eureka: false
                                  # Cannot execute request on any known serverz 一直在控制台刷日志
                                  # eureka本身也是一个服务，默认也会注册到eureka上，但是没什么意思，因此去掉
    fetch-registry: false         #不通过eureka获服务的注册信息

security:
  basic:
    enabled: false  # 增加eureka的访问权限控制
