server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8080/eureka/
spring:
  application:
    name: apollo-config-8081-local

apollo:
  meta: http://127.0.0.1:8080